### ISSUE TITLE
View [themes.default.atom] not found.

### ISSUE THREAD

**Issue by Chumper** [wardrobecms/core-archived#11]
I installed the cms with the style "blocky" and added a new entry.
Then i called `localhost/rss` and get this message:

View [themes.default.atom] not found.

It also seems that the different atom files in the themes folder are messed up.

**Comment by rtablada** [comment]
Yeah, I think that we can go with a default atom within core. @ericbarnes do you see a need to make the atom feed configurable? Not too savvy on RSS stuff so not sure either way.

**Comment by ericlbarnes** [comment]
I would prefer it configurable since some may want only partial text. Plus that would give the most flexibility in the future. 

```
I can actually think of a few more edge case reasons but yeah I thinks important. :smile: 

—
```

Eric Barnes

**Comment by rtablada** [comment]
Maybe make the default from the original as core::atom and then it is still fully available to modify in theme/atom

**Comment by rtablada** [comment]
Eric, I'm still contemplating if the atom view should extend core::atom instead so that if people clear out the default them they don't break their app?

**Comment by ericlbarnes** [comment]
I don't think that's a big deal. If they delete or clear out the default then I kind of feel like it would be on them. I only reference the parent in these because I was tired of editing the same file three times to adjust. 

However, this kind of touches on a bigger feature in allowing theme fallbacks. What I mean is that lets say they have a custom theme and they didn't create a needed view then it would fallback on a core view. So lets say you just want a style sheet and a layout for your theme then that would be all that's required. I don't think this is a priority right now though just some thoughts I had.
